- apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/apt-releases-hashicorp-com.gpg

- shell: lsb_release -cs
  register: lsb_release

- apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main"

- apt:
    pkg:
      - software-properties-common
      - terraform
    update_cache: yes
