- apt:
    pkg:
      - software-properties-common
      - gnupg
    update_cache: yes

- apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/apt-releases-hashicorp-com.gpg

- shell: lsb_release -cs
  register: lsb_release

- apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/apt-releases-hashicorp-com.gpg] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main"

- apt:
    pkg:
      - terraform
    update_cache: yes

- shell: bash -ic 'terraform -install-autocomplete'
