- apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg
    update_cache: yes

- get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/cloud.google.gpg

- apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main

- apt:
    pkg:
      - google-cloud-cli
      - google-cloud-sdk-gke-gcloud-auth-plugin
    update_cache: yes
