remote_host: "{{ lookup('env', 'REMOTE_HOST') }}"
private_key_file_path: "/root/.ssh/{{ lookup('env', 'SSH_KEY') }}"

private_key_github: "{{ vault_private_key_github }}"

git_config_name: "{{ vault_git_config_name }}"
git_config_email: "{{ vault_git_config_email }}"

dev_host: "{{ vault_dev_host }}"

docker_hub_username: "{{ vault_docker_hub_username }}"
docker_hub_password: "{{ vault_docker_hub_password }}"

cloudflare_email: "{{ vault_cloudflare_email }}"
cloudflare_api_key: "{{ vault_cloudflare_api_key }}"

stripe_api_key: "{{ vault_stripe_api_key }}"
stripe_publishable_key: "{{ vault_stripe_publishable_key }}"
