- copy:
    dest: ~/.ssh/dev_machine
    content: "{{ private_key_github }}"
    mode: '0600'

- blockinfile:
    path: ~/.ssh/config
    block: |
      Host github.com
       IdentityFile ~/.ssh/dev_machine
    create: yes
    mode: '0600'
