- apt:
    pkg:
      - curl
      - ca-certificates
    update_cache: yes

- get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg

- apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
    filename: kubernetes

- apt:
    pkg:
      - kubectl
    update_cache: yes

- shell: bash -ic 'kubectl completion bash'
  register: kubectl_completion_bash

- blockinfile:
    path: /etc/bash_completion.d/kubectl
    block: "{{ kubectl_completion_bash.stdout }}"
    create: yes
