- apt:
    pkg:
      - tmux
    update_cache: yes

- git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: ~/.tmux

- file:
    src: ~/.tmux/.tmux.conf
    dest: ~/.tmux.conf
    state: link
    force: yes

- copy:
    src: ~/.tmux/.tmux.conf.local
    dest: ~/
    remote_src: yes
    force: false

- blockinfile:
    path: ~/.zshrc.d/tmux.zshrc
    block: |
      alias dev='tmux attach -t dev || tmux new -s dev'
      alias fixssh='eval $(tmux showenv -s SSH_AUTH_SOCK)'
      alias fixsshsock='export SSH_AUTH_SOCK=$(ls -t /tmp/ssh-**/* | head -1)'
    create: yes
