- name: Install docker compose
  block:
    - file:
        path: "{{ docker_plugins_path }}"
        state: directory
    - get_url:
        url: "https://github.com/docker/compose/releases/download/{{ version }}/docker-compose-linux-x86_64"
        dest: "{{ docker_plugins_path }}/docker-compose"
        mode: "+x"
    - file:
        src: "{{ docker_plugins_path }}/docker-compose"
        dest: /usr/local/bin/docker-compose
        state: link
  vars:
    docker_plugins_path: "{{ ansible_env.HOME }}/.docker/cli-plugins"
