- name: Install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "+x"

- name: Install docker compose v2
  block:
    - file:
        path: "{{ docker_plugins_path }}"
        state: directory
    - get_url:
        url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
        dest: "{{ docker_plugins_path }}/docker-compose"
        mode: "+x"
  vars:
    docker_plugins_path: "{{ ansible_env.HOME }}/.docker/cli-plugins"
