- blockinfile:
    path: ~/.bashrc.d/ps1.bashrc
    block: |
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ [\1]/'
      }

      PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\e[0;33m\]$(parse_git_branch) \[\033[00m\]\$ '
    create: yes
