- name: Setup dev-machine
  hosts: all
  gather_facts: yes

  pre_tasks:
    - name: Update apt packages
      apt:
        pkg:
          - curl
          - gnupg
          - make
          - mc
        update_cache: yes

  roles:
    - role: secrets
    - role: bashrc
    - role: ps1

    - role: git
      config:
        name: "{{ git_config_name }}"
        email: "{{ git_config_email }}"

    - role: fzf
    - role: tmux
    - role: terraform
    - role: kubectl
    - role: helm
    - role: google-cloud-sdk

    - role: docker-compose
      version: v2.4.1

    - role: asdf
      version: v0.10.0
      plugins:
        - name: nodejs
          versions:
            - 16.15.0
          global: 16.15.0
        - name: ruby
          versions:
            - 3.1.2
          global: 3.1.2

    - role: hexlet
      config:
        dev_host: "{{ dev_host }}"
        git_user: "{{ git_config_name }}"
        git_email: "{{ git_config_email }}"
        docker_hub_username: "{{ docker_hub_username }}"
        docker_hub_password: "{{ docker_hub_password }}"
        cloudflare_email: "{{ cloudflare_email }}"
        cloudflare_api_key: "{{ cloudflare_api_key }}"
        stripe_api_key: "{{ stripe_api_key }}"
        stripe_publishable_key: "{{ stripe_publishable_key }}"

  tasks:
    # TODO: use https://docs.ansible.com/ansible/latest/collections/community/general/gem_module.html
    - shell: bash -ic 'gem install solargraph'
