- name: Setup dev-machine
  hosts: all
  gather_facts: yes

  pre_tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

  roles:
    - role: docker-compose

    # - name: debug
    #   shell: docker compose version
    #   register: command_output

    # - debug:
    #     var: command_output.stdout_lines
