- name: Setup dev-machine
  hosts: all
  gather_facts: yes

  pre_tasks:
    - name: Update apt packages
      apt:
        pkg:
          - curl
          - make
        update_cache: yes

  roles:
    - role: bashrc
    - role: ps1
    - role: fzf

    - role: docker-compose
      version: v2.4.1

    - role: asdf
      version: v0.10.0
      plugins:
        - name: nodejs
          versions:
            - 16.15.0
          global: 16.15.0
        - name: ruby
          versions:
            - 3.1.2
          global: 3.1.2
