- hosts: workstations
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: update and upgrade system
      apt:
        upgrade: safe
        update_cache: yes

    - name: install packages
      apt:
        pkg:
          - curl
          - gnupg
          - zsh
          - fzf
          - direnv
          - mc
          - htop
          - make
        update_cache: yes

    - name: change shell for user
      user:
        name: "{{ remote_host.user }}"
        shell: "/usr/bin/zsh"

- hosts: workstations
  gather_facts: no
  any_errors_fatal: true
  roles:
    - role: git
      config:
        name: "{{ git_config.name }}"
        email: "{{ git_config.email }}"

    - role: asdf
      version: v0.13.1
      plugins:
        - name: nodejs
          versions:
            - 14.21.3
            - 20.11.0
          global: 20.11.0
        - name: ruby
          versions:
            - 3.2.2
          global: 3.2.2

    - role: tmux

    - role: ohmyzsh
      update: yes
      config:
        theme: agnoster
        plugins:
          - git
          - fzf
          - direnv
          - asdf
          - kubectl
          - terraform

#   roles:
#     - role: helm
#     - role: google-cloud-sdk
#     - role: yandex-cli

#     - role: docker-compose
#       version: v2.14.2

#     # TODO: need to update
#     # - role: hexlet
#     #   config:
#     #     dev_host: "{{ dev_host }}"
#     #     git_user: "{{ git_config_name }}"
#     #     git_email: "{{ git_config_email }}"
#     #     docker_hub_username: "{{ docker_hub_username }}"
#     #     docker_hub_password: "{{ docker_hub_password }}"
#     #     cloudflare_email: "{{ cloudflare_email }}"
#     #     cloudflare_api_key: "{{ cloudflare_api_key }}"
#     #     stripe_api_key: "{{ stripe_api_key }}"
#     #     stripe_publishable_key: "{{ stripe_publishable_key }}"

#     # TODO: use https://docs.ansible.com/ansible/latest/collections/community/general/gem_module.html
#     - shell: bash -ic 'gem install solargraph'
