- file:
    path: ~/.bashrc.d
    state: directory

- blockinfile:
    path: ~/.bashrc
    block: |
      # include source files from ~/.bashrc.d directory
      if [ -d ~/.bashrc.d ]; then
        for file in ~/.bashrc.d/*; do
          . "$file"
        done
      fi
